search_space:
  nadir_eps:
    _type: uniform
    _value: [ 0.01, 0.8 ]



trial_command: python psl_main.py --use-nni Y --problem-name vlmop1
trial_code_directory: .

trial_concurrency: 4
max_trial_number: 20

tuner:
  name: TPE
  class_args:
    optimize_mode: maximize

training_service:
  platform: local